### ISSUE TITLE
New Maintainer?

### ISSUE THREAD

**Issue by briarsweetbriar** [adopted-ember-addons/ember-keyboard#101]
Is anyone interested in taking over this project? Unfortunately, I don't have the time to maintain it any longer.

**Comment by buschtoens** [comment]
Thanks for all the effort you have put into it!

You may want to consider transferring the repo to the [`adopted-ember-addons` organization](https://github.com/adopted-ember-addons/program-guidelines).

**Comment by snewcomer** [comment]
Yes this sounds like a great idea for a great addon!

**Comment by lukemelia** [comment]
@briarsweetbriar I'd be happy to take over and to shepherd it into the adopted-ember-addons org

**Comment by briarsweetbriar** [comment]
@lukemelia thanks for the offer, luke. i'll set aside some time this weekend to do it myself, but if it turns out to be a bigger process than that, than i might ask you to help after all.

**Comment by lukemelia** [comment]
The transition to the adopted-ember-addons org has been completed. Thank you for your stewardship of the project over the years, @briarsweetbriar.
