### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by lukemelia** [adopted-ember-addons/ember-keyboard#116]
Concurrent with this project becoming part of the adopted-ember-addons org, I've volunteered to help do some of the maintainership. My number one goal is to help the addon catch up to modern Ember APIs so users have an upgrade path when migrating their apps to octane. Here's a proposed roadmap to get us there:

* 5.0.0 - current stable version
* 6.0.0.beta.0 * Released ✅ 
  - Drop support for Ember older than 3.8 #110 (Update: merged ✅)
  - Add on-keyboard and keyboard-shortcut element modifiers and promote keyboard-press component #111 (Update: merged ✅)
* 6.0.0.beta.1 * Released ✅ 
  - Fix for #122 (may require breaking change to software keyboard remapping support) (Update: fixed ✅)
  - New API #135 (Update: merged ✅)
  - Deprecate has/trigger responder API #135 (Update: merged ✅)
  - Deprecate on-keyboard, keyboard-shortcut element modifiers and keyboard-press component from 6.0.0-beta.0 in favor on-key helper & modifier #135 (Update: merged ✅)
  - Deprecate the initializer that reopens TextArea and TextField with config-based opt-out (Update: merged ✅)
  - Add non-mixin API recommended for adding keyboard event handling to controllers and routes (help wanted #115) (Update: merged ✅)
  - Deprecate mixin usage (Update: merged ✅)
* 6.0.0 * Released ✅ 
  - Everything in the beta above
* 6.0.3 * Released ✅ 
  - Update dependencies for better ecosystem compatibility
* 6.0.4 * Released ✅ 
  - Deprecate the old propagation model #164
* [7.0.0.beta.0](https://github.com/adopted-ember-addons/ember-keyboard/releases/tag/v7.0.0-beta.0) * Released ✅ 
  - Drop mixins from the codebase
  - Drop deprecated features from 6.0.0-beta.0: keyboard-press, on-keyboard, and keyboard-shortcut
  - Drop old propagation model from the codebase and warn that the configuration can be removed
  - Drop has/trigger responder API
  - Drop the initializer and warn that the configuration can be removed
* 7.0.0 * Released ✅ 
  - Everything in the beta above
* 7.0.1 * Released ✅ 
  - #557 disableOnInputFields option
* 7.0.2
  - #558 improved shadow DOM support
* Beyond?

**Comment by bertdeblock** [comment]
Maybe these can be ditched as well?
https://github.com/adopted-ember-addons/ember-keyboard/blob/master/addon/index.js#L5-L15
They seem to have been present like this for a while, so seems safe to drop these in the next major?
