### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by btecu** [adopted-ember-addons/ember-keyboard#283]
On release `6.0.1`, using the helper version:
```
{{on-key "cmd+o" this.someAction}}
```

When pressing any key, it throws an error:
```
TypeError: Object doesn't support property or method 'from'
```

**Comment by lukemelia** [comment]
@btecu ember-keyboard 6 drops support for IE. I'll make sure this gets documented in the README.

**Comment by lukemelia** [comment]
Updated README in #285
