### ISSUE TITLE
keyResponder wrapped classic components missing component arguments

### ISSUE THREAD

**Issue by bjornharrtell** [adopted-ember-addons/ember-keyboard#451]
We've been trying to upgrade to 6.x with the method described at http://adopted-ember-addons.github.io/ember-keyboard/deprecations but we get an unexpected problem in that component arguments becomes undefined. I've made a reproduction repository at https://github.com/bjornharrtell/ek-repro and the problem is specifically noted here:

https://github.com/bjornharrtell/ek-repro/blob/4f01de4646ec385490daa55643a03008b5859a69/app/components/withk.js#L7

While an otherwise identical component without keyResponder wrapping works as expected at https://github.com/bjornharrtell/ek-repro/blob/4f01de4646ec385490daa55643a03008b5859a69/app/components/withoutk.js#L6.

**Comment by bjornharrtell** [comment]
Obsolete, I think.

**Comment by KeithKosh** [comment]
@bjornharrtell I'm still encountering this issue. I'm running 8.2.1 of `ember-keyboard` and I have a classic component with two arguments passed in, but when I wrap it in `keyResponder` the two arguments always return `undefined`. (It doesn't matter if I use `get(this, 'argumentName')` or `this.argumentName`)

**Comment by bjornharrtell** [comment]
@KeithKosh mm yes I think perhaps we migrated away from classic components everywhere.
