### ISSUE TITLE
route usage: docs example / query

### ISSUE THREAD

**Issue by nruth** [adopted-ember-addons/ember-keyboard#52]
I'd like to PR this, but would appreciate a sanity check.

The docs example at the moment works for components, but doesn't warn that strange things will happen if you copy-paste that into a route, which devs unfamiliar with ember lifecycle hooks are bound to do, pardon the pun. 

The trouble is that leads to shortcuts executing on pages that they shouldn't, because the routes are singletons and seem to stay registered "forever".

```
 activateKeyboard: Ember.on('init', function() {
    this.set('keyboardActivated', true);
  })
```

This seems to work, though I'm not entirely confident with the hooks myself so would like a second opinion before writing it up:

```
  activateKeyboard: Ember.on('activate', function() {
    this.set('keyboardActivated', true);
  }),

  deactivateKeyboard: Ember.on('deactivate', function() {
    this.set('keyboardActivated', false);
  }),
```

**Comment by null-null-null** [comment]
Yeah, that looks like it would work. It might be worth changing the `activate-keyboard-on-insert` mixin to look like this:

```js
import Ember from 'ember';

const {
  Mixin,
  on,
  set
} = Ember;

export default Mixin.create({
  didInsertElement(...args) {
    this._super(...args);

    set(this, 'keyboardActivated', true);
  },

  activate(...args) {
    this._super(...args);

    set(this, 'keyboardActivated', true);
  },

  deactivate(...args) {
    this._super(...args);

    set(this, 'keyboardActivated', false);
  }
```

**Comment by lukemelia** [comment]
Closing in favor of #114
