### ISSUE TITLE
Package version is still `6.0.3`

### ISSUE THREAD

**Issue by bertdeblock** [adopted-ember-addons/ember-keyboard#531]

**Comment by SergeAstapov** [comment]
@bertdeblock did you mean `version` field in `package.json` or smth else? https://www.npmjs.com/package/ember-keyboard has `6.0.4`

**Comment by bertdeblock** [comment]
I noticed on `master` it still has 6.0.3.

**Comment by SergeAstapov** [comment]
@bertdeblock we published `6.0.4` version from `v6` branch which had only cherry picked commits from `master` and didn't bother merging back as nothing is "lost" in master and we planned to release v7 beta.0 real soon
