### ISSUE TITLE
Not compatible with Ember 4

### ISSUE THREAD

**Issue by NullVoxPopuli** [adopted-ember-addons/ember-keyboard#565]
Got a deprecation on 3.28 about using `@ember/legacy-bulit-in-components` for TextArea.
But, why is ember-keyboard using textarea?

**Comment by SergeAstapov** [comment]
@NullVoxPopuli which version of the addon are you using? `v7.0.0-beta.0` is what you need for Ember v4 compatibility

**Comment by NullVoxPopuli** [comment]
oh! I didn't know there was a beta. _noice_!
I'll give it a go

**Comment by SergeAstapov** [comment]
@NullVoxPopuli I think we would need to land #557. Other than that - does not seem we have any other issues.

Wonder if @lukemelia has any other things before we land stable release?

**Comment by lukemelia** [comment]
@SergeAstapov @NullVoxPopuli I don't think #557 is a requirement to make 7.0.0 stable. I'll do it now.

**Comment by lukemelia** [comment]
Released!

**Comment by NullVoxPopuli** [comment]
Yay! Thank you!
