### ISSUE TITLE
keyArray.sort is not a function

### ISSUE THREAD

**Issue by svdsande** [adopted-ember-addons/ember-keyboard#692]
I installed version `7.0.1` and I am trying to trigger an action based on a given key press. The example below results in the following error: _TypeError: keyArray.sort is not a function_
~~~hbs
{{on-key "KeyB" (action "onKeyPress")}}`
~~~

The error occurs in `listener-name` util. I am not sure if I am missing something.
Let me know if I could help in any way.

**Comment by lukemelia** [comment]
@svdsande I tried to reproduce your issue in a test (https://github.com/adopted-ember-addons/ember-keyboard/pull/new/svdsande-repro-attempt) but it passed. Please take a look at that branch and see if you can create a reproduction / failing test.

**Comment by svdsande** [comment]
@lukemelia Thanks for the quick response! I will try to create a reproducible scenario based on that branch. Will keep you posted 👍

**Comment by svdsande** [comment]
Looks like my setup was incorrect 🙈 So this issue is not relevant. Thanks for the help.
