### ISSUE TITLE
Question mark?

### ISSUE THREAD

**Issue by samselikoff** [adopted-ember-addons/ember-keyboard#71]
I tracked down [this PR](https://github.com/patience-tema-baron/ember-keyboard/commit/838873b339014f39752e928c7365dd38937e1934#diff-30a6e543ac444bcb73717e59754ce525) which added the question mark. Did it get lost in some refactoring? If so I'll add it back

**Comment by patience-tema-baron** [comment]
It's been awhile, but I believe that was taken out in the migration to `2.0`, as we went from using `key` to `code`. Would `shift+Slash` work, instead?

**Comment by lukemelia** [comment]
I added an example to our tests in #119. `shift+Slash` is the way to go.
