### ISSUE TITLE
Update to `@ember/test-helpers` 3.x

### ISSUE THREAD

**Issue by boris-petrov** [adopted-ember-addons/ember-keyboard#729]
Version 3.0.2 of `@ember/test-helpers` is out so it would be nice to update the version required by the addon [here](https://github.com/adopted-ember-addons/ember-keyboard/blob/v8.2.0/addon/package.json#L58).

**Comment by boris-petrov** [comment]
I believe this has been fixed. Just a new release is needed. Thanks!

**Comment by charlesfries** [comment]
@SergeAstapov Are you able to make a release in the near future? Thank you!

**Comment by SergeAstapov** [comment]
@charlesfries I don't have access on npm, @lukemelia woudl you be able to help with release?

**Comment by lukemelia** [comment]
Released in 8.2.1
