### ISSUE TITLE
Addon's ember-source incompatible with Ember 5

### ISSUE THREAD

**Issue by Elawphant** [adopted-ember-addons/ember-keyboard#744]
Please fix the ember-source dependency

**Comment by SergeAstapov** [comment]
@Elawphant sorry could you be little bit more specific? `ember-source` is not listed in `dependencies` nor `peerDependencies` of this addon see https://github.com/adopted-ember-addons/ember-keyboard/blob/master/addon/package.json

**Comment by Elawphant** [comment]
hmm. very strange.
I have removed my node_modules and trying to reinstall with all fresh dependencies. I got an error with this one too. But seems it should have not have risen.

**Comment by NullVoxPopuli** [comment]
looks like this is resolved?

**Comment by SergeAstapov** [comment]
Closing until we have a reproduction as issue reported here seems unrelated to `ember-keyboard`
