### ISSUE TITLE
alt doesn't work at all (mac) when upgrading from v3 to v4

### ISSUE THREAD

**Issue by optikalefx** [adopted-ember-addons/ember-keyboard#93]
On mac chrome, I upgraded from 3.0 to 4.0 and alt no longer works. In any configuration. Either AltLeft, alt or AltRight. It works just fine with any other key and any other modifier.

**Comment by bitwolfe** [comment]
I just ran into this issue as well, also on a Mac Chrome. No special keymap in use, just default. No Alt combinations work.

Going back to v3 makes Alt work again.

**Comment by lukemelia** [comment]
Confirmed bug. Reproduced with a failing test in #122

**Comment by optikalefx** [comment]
This is fixed by my PR #117

**Comment by lukemelia** [comment]
Fixed by #135
