### ISSUE TITLE
Deprecation warning: @each

### ISSUE THREAD

**Issue by pixelmatrix** [adopted-ember-addons/ember-keyboard#95]
https://github.com/patience-tema-baron/ember-keyboard/blob/d78de0b27e1d7dcefef20e141991d72d716997cb/addon/services/keyboard.js#L33

We're getting a deprecation warning in the latest versions of Ember 3 due to the line above. Any chance this package could be updated to stay compatible? https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_getting-the-each-property

**Comment by lukemelia** [comment]
This will be addressed by #111

**Comment by lukemelia** [comment]
#111 has been merged and will be released in v6.0.0
