### ISSUE TITLE
Incorrect Documentation Around Test Helpers

### ISSUE THREAD

**Issue by Emerson** [adopted-ember-addons/ember-keyboard#99]
Howdy,

Firstly, thanks for this awesome library, it's been really nice to use. In the process of trying to upgrade and running into a problem.

After trying to upgrade to `4.x` I'm not able to run my acceptance tests anymore. In the [documentation](http://patience-tema-baron.github.io/ember-keyboard/#/testing) it mentions that we need to import:

```js
import keyboardRegisterTestHelpers from './ember-keyboard/register-test-helpers';
```

But that module does not appear to exist. In fact, if I inspect the entire tree of available modules I don't see anything relating to registering test helpers.

![Screenshot 2019-05-28 11 18 11](https://user-images.githubusercontent.com/186545/58489983-53787400-813a-11e9-90e7-53c413fc6fc5.png)

Am I missing something basic here? Let me know,
Thanks!

**Comment by lukemelia** [comment]
Thanks for flagging this @Emerson. I updated the docs in #120
